import { useState, type ReactNode } from "react";
import { Bell, Check, CheckCircle2, ChevronRight, Clock3, Edit3, Flame, ImagePlus, Minus, PackageCheck, Plus, Power, ReceiptText, Save, Settings2, ShoppingBag, UploadCloud, X } from "lucide-react";

type View = "queue" | "production" | "menu" | "store";
type Stage = "pending" | "processing" | "ready" | "canceled";
type Order = { id: string; customer: string; total: string; stage: Stage; items: string[]; note: string };
const startingOrders: Order[] = [
  { id: "#D-4187", customer: "Maya R.", total: "$28.40", stage: "pending", items: ["6 Maple Old Fashioned", "2 Ube Glaze"], note: "Awaiting receipt photo" },
  { id: "#D-4189", customer: "J. Patel", total: "$16.20", stage: "pending", items: ["Boston Cream box", "2 Iced latte"], note: "Cash proof requested" },
  { id: "#D-4183", customer: "North Office", total: "$94.00", stage: "processing", items: ["24 Assorted", "Cold brew traveler"], note: "Driver: Lena · 18:50" },
  { id: "#D-4184", customer: "Sam C.", total: "$12.75", stage: "processing", items: ["3 Churro Rings", "1 Espresso"], note: "No cinnamon dust" },
  { id: "#D-4178", customer: "Ari L.", total: "$36.50", stage: "ready", items: ["Dozen Classic", "2 Strawberry Milk"], note: "Pickup shelf B" },
  { id: "#D-4179", customer: "Hotel Vale", total: "$72.80", stage: "ready", items: ["18 Vegan Glaze", "6 Cruffins"], note: "Courier waiting" },
];
const initialProducts = [
  { name: "Black Sesame Halo", sku: "NO-SES-001", price: "4.80", stock: true },
  { name: "Vanilla Bean Cloud", sku: "NO-VAN-002", price: "3.90", stock: true },
  { name: "Salted Yuzu Cruller", sku: "NO-YUZ-003", price: "5.20", stock: false },
  { name: "Cacao Nib Brioche", sku: "NO-CAC-004", price: "4.60", stock: true },
];
const labels: Record<View, { name: string; eyebrow: string }> = { queue: { name: "Order Queue", eyebrow: "LIVE FULFILLMENT" }, production: { name: "Production", eyebrow: "KITCHEN CONTROL" }, menu: { name: "Menu Management", eyebrow: "CATALOG CONTROL" }, store: { name: "Store Operations", eyebrow: "STORE CONTROL" } };

export function DashboardScreen() {
  const [view, setView] = useState<View>("queue");
  const [orders, setOrders] = useState(startingOrders);
  const [products, setProducts] = useState(initialProducts);
  const [targets, setTargets] = useState({ classics: 96, premium: 48, boxes: 18 });
  const [forceClosed, setForceClosed] = useState(false);
  const [notice, setNotice] = useState("Live dashboard ready.");
  const stageOrder: Record<Stage, Stage> = { pending: "processing", processing: "ready", ready: "canceled", canceled: "canceled" };
  const advance = (order: Order) => { const next = stageOrder[order.stage]; setOrders((all) => all.map((item) => item.id === order.id ? { ...item, stage: next } : item)); setNotice(`${order.id} moved to ${next}.`); };
  const save = (message: string) => setNotice(message);

  return <section className="min-w-0 px-6 py-7 lg:px-9 xl:px-10">
    <header className="flex flex-col gap-5 border-b border-white/[0.09] pb-6 xl:flex-row xl:items-end xl:justify-between"><div><p className="font-mono text-[11px] tracking-[0.14em] text-[#e8ad59]">NIGHT OVEN · COMMAND CENTER</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.035em] text-stone-100">Store Dashboard</h1><p className="mt-2 text-sm text-stone-500">View and update every live operating surface from one workspace.</p></div><div className="flex items-center gap-3"><span className={`rounded-xl border px-3 py-2 text-xs ${forceClosed ? "border-[#bb6664]/30 bg-[#512d2e]/35 text-[#d9948f]" : "border-[#8dd2ae]/25 bg-[#8dd2ae]/10 text-[#9ed8b4]"}`}><span className={`mr-2 inline-block size-1.5 rounded-full ${forceClosed ? "bg-[#bb6664]" : "bg-[#8dd2ae]"}`} />{forceClosed ? "Store paused" : "Store accepting orders"}</span><button className="grid size-10 place-items-center rounded-xl border border-white/10 bg-[#1a1a1a] text-stone-400"><Bell size={18} /></button></div></header>
    <nav className="mt-6 flex gap-2 overflow-x-auto border-b border-white/[0.09] pb-4" aria-label="Dashboard workspaces">{([{ key: "queue", icon: ReceiptText }, { key: "production", icon: Flame }, { key: "menu", icon: ShoppingBag }, { key: "store", icon: Settings2 }] as const).map(({key,icon: Icon}) => <button key={key} onClick={() => setView(key)} className={`flex shrink-0 items-center gap-2 rounded-xl border px-4 py-2.5 text-sm transition ${view === key ? "border-[#e5ad57]/35 bg-[#e5ad57] text-[#291a0c]" : "border-white/10 bg-[#1a1a1a] text-stone-400 hover:text-stone-200"}`}><Icon size={16} />{labels[key].name}</button>)}</nav>
    {notice && <div className="mt-5 flex items-center justify-between rounded-xl border border-[#8dd2ae]/25 bg-[#8dd2ae]/10 px-4 py-3 text-sm text-[#a7dfbd]"><span>{notice}</span><button onClick={() => setNotice("")}><X size={16} /></button></div>}
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<ReceiptText size={16} />} label="Open orders" value={String(orders.filter((order) => order.stage !== "canceled").length)} detail="4 since 17:00" /><Metric icon={<Clock3 size={16} />} label="Kitchen average" value="14m" detail="Target: under 16m" /><Metric icon={<PackageCheck size={16} />} label="Ready for pickup" value={String(orders.filter((order) => order.stage === "ready").length)} detail="Oldest waiting 7m" /><Metric icon={<Flame size={16} />} label="Today’s sales" value="$1,284" detail="12.8% vs Tue" /></div>
    <section className="mt-7"><p className="font-mono text-[10px] tracking-[0.14em] text-[#e8ad59]">{labels[view].eyebrow}</p><h2 className="mt-1 text-xl font-semibold">{labels[view].name}</h2>{view === "queue" && <Queue orders={orders} advance={advance} />}{view === "production" && <Production targets={targets} setTargets={setTargets} save={save} />}{view === "menu" && <Menu products={products} setProducts={setProducts} save={save} />}{view === "store" && <Store forceClosed={forceClosed} setForceClosed={setForceClosed} save={save} />}</section>
  </section>;
}

function Queue({ orders, advance }: { orders: Order[]; advance: (order: Order) => void }) { const columns: { stage: Stage; title: string; tint: string; dot: string }[] = [{stage:"pending",title:"Pending Evidence",tint:"text-[#efbd69]",dot:"bg-[#e8ad55]"},{stage:"processing",title:"Processing",tint:"text-[#9fc2dd]",dot:"bg-[#8db7d8]"},{stage:"ready",title:"Ready",tint:"text-[#9ed8b4]",dot:"bg-[#8dd2ae]"},{stage:"canceled",title:"Canceled",tint:"text-[#d9948f]",dot:"bg-[#bb6664]"}]; return <div className="mt-5 grid gap-4 2xl:grid-cols-4 xl:grid-cols-2">{columns.map((column) => <div key={column.stage} className="rounded-2xl border border-white/[0.09] bg-[#161616] p-3"><div className="flex items-center justify-between px-1 pb-4"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${column.dot}`} /><h3 className={`text-sm font-semibold ${column.tint}`}>{column.title}</h3></div><span className="font-mono text-xs text-stone-600">{orders.filter((o) => o.stage === column.stage).length}</span></div><div className="space-y-3">{orders.filter((o) => o.stage === column.stage).map((order) => <article key={order.id} className="rounded-xl border border-white/[0.09] bg-[#1d1d1d] p-3.5"><div className="flex justify-between"><div><p className="font-mono text-[10px] text-stone-600">{order.id}</p><h4 className="mt-1 text-sm font-medium">{order.customer}</h4></div><strong className="font-mono text-sm">{order.total}</strong></div><div className="mt-3 space-y-1">{order.items.map((item) => <p key={item} className="text-xs text-stone-500">• {item}</p>)}</div><p className="mt-3 border-t border-white/[0.07] pt-2 text-[11px] text-stone-600">{order.note}</p>{order.stage !== "canceled" && <button onClick={() => advance(order)} className="mt-3 flex w-full items-center justify-center gap-1 rounded-lg border border-white/10 py-1.5 text-[11px] text-stone-400 hover:border-[#e5ad57]/35 hover:text-[#f2bd67]">Advance order <ChevronRight size={13} /></button>}</article>)}</div></div>)}</div> }

function Production({ targets, setTargets, save }: { targets: {classics:number;premium:number;boxes:number}; setTargets: (next:{classics:number;premium:number;boxes:number})=>void; save:(message:string)=>void }) { const rows: [keyof typeof targets,string,string][] = [["classics","Classic rings","78 baked"],["premium","Premium specials","32 baked"],["boxes","Boxed orders","11 packed"]]; return <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-white/[0.09] bg-[#1a1a1a] p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Today’s bake plan</h3><p className="mt-1 text-xs text-stone-500">Adjust the target count for each production line.</p></div><Flame className="text-[#e8ad59]" /></div><div className="mt-6 space-y-4">{rows.map(([key,name,done]) => <div key={key} className="rounded-xl border border-white/[0.08] bg-[#202020] p-4"><div className="flex items-center justify-between"><div><p className="text-sm text-stone-200">{name}</p><p className="mt-1 text-xs text-stone-600">{done}</p></div><div className="flex items-center gap-2"><button onClick={() => setTargets({...targets,[key]:Math.max(0,targets[key]-6)})} className="grid size-8 place-items-center rounded-lg border border-white/10 text-stone-400"><Minus size={14}/></button><span className="w-9 text-center font-mono text-sm">{targets[key]}</span><button onClick={() => setTargets({...targets,[key]:targets[key]+6})} className="grid size-8 place-items-center rounded-lg border border-white/10 text-stone-400"><Plus size={14}/></button></div></div><div className="mt-3 h-1.5 rounded-full bg-black/30"><div className="h-full rounded-full bg-[#e8ad55]" style={{width:`${Math.min(100, Math.round((key === "classics" ? 78 : key === "premium" ? 32 : 11) / targets[key] * 100))}%`}} /></div></div>)}</div><button onClick={() => save("Production plan saved for today’s shift.")} className="mt-5 flex h-11 items-center justify-center gap-2 rounded-xl bg-[#8dd2ae] px-4 text-sm font-semibold text-[#10251c]"><Save size={16}/>Save production plan</button></section><section className="rounded-2xl border border-white/[0.09] bg-[#1a1a1a] p-5"><h3 className="font-semibold">Quick production actions</h3><div className="mt-4 space-y-2"><Action label="Add emergency batch" icon={<Plus size={15}/>} action={() => save("Emergency batch added to the production plan.")} /><Action label="Print bake list" icon={<ReceiptText size={15}/>} action={() => save("Bake list sent to the kitchen printer.")} /><Action label="Update staff handoff" icon={<Edit3 size={15}/>} action={() => save("Production handoff updated.")} /></div></section></div> }

function Menu({ products, setProducts, save }: { products: typeof initialProducts; setProducts: (next:typeof initialProducts)=>void; save:(message:string)=>void }) { return <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{products.map((product,index) => <article key={product.sku} className="rounded-2xl border border-white/[0.09] bg-[#1a1a1a] p-4"><div className="grid h-28 place-items-center rounded-xl bg-[#242424]"><div className="grid size-16 place-items-center rounded-full bg-[#c98240]"><div className={`size-12 rounded-full ${index%2 ? "bg-[#f5dfb9]" : "bg-[#4d2921]"}`} /></div></div><input value={product.name} onChange={(e) => setProducts(products.map((item,i) => i===index ? {...item,name:e.target.value} : item))} className="mt-4 w-full bg-transparent text-sm font-semibold outline-none" /><p className="mt-1 text-xs text-stone-500">{product.sku} · From ${product.price}</p><div className="mt-4 flex items-center justify-between rounded-xl bg-[#202020] px-3 py-2.5"><span className="text-xs text-stone-300">{product.stock ? "In Stock" : "Out of Stock"}</span><button onClick={() => setProducts(products.map((item,i)=> i===index ? {...item,stock:!item.stock} : item))} className={`relative h-6 w-11 rounded-full ${product.stock ? "bg-[#8dd2ae]" : "bg-[#8e5250]"}`}><span className={`absolute top-0.5 size-5 rounded-full bg-white transition ${product.stock ? "left-5" : "left-0.5"}`} /></button></div><label className="mt-3 flex items-center gap-2 text-xs text-stone-500">Price $<input value={product.price} onChange={(e) => setProducts(products.map((item,i) => i===index ? {...item,price:e.target.value} : item))} className="h-9 min-w-0 flex-1 rounded-lg border border-white/10 bg-[#202020] px-2 font-mono text-stone-200 outline-none" /></label></article>)}<button onClick={() => save("Menu changes saved and pushed to POS.")} className="md:col-span-2 xl:col-span-4 flex h-11 items-center justify-center gap-2 rounded-xl bg-[#8dd2ae] text-sm font-semibold text-[#10251c]"><Save size={16}/>Save menu availability & prices</button></div> }

function Store({ forceClosed, setForceClosed, save }: { forceClosed:boolean; setForceClosed:(value:boolean)=>void; save:(message:string)=>void }) { const [opening,setOpening]=useState("07:00"); const [closing,setClosing]=useState("22:00"); return <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-white/[0.09] bg-[#1a1a1a] p-5"><h3 className="font-semibold">Store hours</h3><p className="mt-1 text-xs text-stone-500">Set today’s customer ordering window.</p><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-xs text-stone-500">Open<input type="time" value={opening} onChange={(e)=>setOpening(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-[#202020] px-3 text-stone-100 outline-none" /></label><label className="text-xs text-stone-500">Close<input type="time" value={closing} onChange={(e)=>setClosing(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-[#202020] px-3 text-stone-100 outline-none" /></label></div><button onClick={() => save(`Store hours saved: ${opening}–${closing}.`)} className="mt-5 flex h-11 items-center justify-center gap-2 rounded-xl bg-[#8dd2ae] px-4 text-sm font-semibold text-[#10251c]"><Save size={16}/>Save hours</button></section><section className="rounded-2xl border border-[#bb6664]/20 bg-[#1a1a1a] p-5"><h3 className="font-semibold">Emergency controls</h3><p className="mt-2 text-xs leading-5 text-stone-500">Pause new customer orders instantly while preserving the queue already in production.</p><button onClick={() => {const next=!forceClosed; setForceClosed(next); save(next ? "Store paused. New online orders are blocked." : "Store reopened for new orders.");}} className={`mt-6 flex h-11 w-full items-center justify-center gap-2 rounded-xl border text-sm ${forceClosed ? "border-[#8dd2ae]/30 bg-[#8dd2ae]/10 text-[#9ed8b4]" : "border-[#bb6664]/35 bg-[#512d2e]/35 text-[#d9948f]"}`}>{forceClosed ? <><CheckCircle2 size={16}/>Reopen store</> : <><Power size={16}/>Force close store</>}</button></section></div> }
function Action({label,icon,action}:{label:string;icon: ReactNode;action:()=>void}) { return <button onClick={action} className="flex w-full items-center justify-between rounded-xl border border-white/[0.08] bg-[#202020] px-3 py-3 text-left text-sm text-stone-300 hover:border-[#e5ad57]/35"><span className="flex items-center gap-2">{icon}{label}</span><ChevronRight size={15} className="text-stone-600"/></button> }
function Metric({ icon, label, value, detail }: { icon: ReactNode; label: string; value: string; detail: string }) { return <section className="rounded-2xl border border-white/[0.09] bg-[#1a1a1a] p-4"><div className="flex justify-between text-stone-500"><p className="text-xs">{label}</p><span className="text-[#e9ad55]">{icon}</span></div><p className="mt-3 font-mono text-2xl font-semibold text-stone-100">{value}</p><p className="mt-1 text-[11px] text-stone-600">{detail}</p></section> }
